spring:
  datasource:
    url: jdbc:h2:file:C:/data/useraccountdb
    username: admin
    password: admin
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


  security:
    user:
      name: ilqar
      password: ilqar123

jwt:
 secret: javainusesecretKeyForSignatureAlgorithmHS256methodcreatecreatecreatecreate



